/*
 * Agent-facing contracts. Each one is attached only to the tools that write the data it governs, so the
 * tool list stays small; the server instructions only route natural-language requests to tools.
 */

export const serverInstructions = [
  "Work Intelligence is a local-first, explicit-opt-in work record system. Only projects the user marked as tracked are read or written; unregistered, paused, and ignored projects are quietly skipped, and you must never read their source, handoff, Git, or evidence.",
  "Before preparing a finalize payload for a workspace, call work_get_project_status; if it is not tracked, do not record the work.",
  "Routing: save finished work → work_finalize_session. Recover context → work_get_context (pass task/paths before starting work; also lists pending Agent requests). Past work, gotchas, or an error seen before → work_recall, then work_get_session. List Sessions by date → work_list_sessions. Fix a saved summary → work_update_session_summary (replace/append); fix the five-section workSummary → work_update_session_work_summary (replace needs all five sections, patch accepts some). Never use evidence as a substitute for a summary update. A finalize idempotency conflict means the summary changed: use work_update_session_summary.",
  "Report synthesis (整理、提煉、產生或完成工作報告): use the newest pending request; if none exists, create one with work_request_report_synthesis; if the newest one failed or was interrupted, retry it; then get its context and save the summary under the work_save_report_summary contract.",
  "Metadata gaps (補齊、更新、檢查或處理 metadata 缺口): use the newest pending or processing request; if none exists, create one with work_request_metadata_backfill; then get its context, inspect the real worktree/diff or handoff, and apply only confirmed values under the work_apply_metadata_backfill contract.",
  "The user should only need natural language: never ask them for tool names, request IDs, JSON, or call order. Keep deterministic reports separate from Agent-derived summaries. If context is insufficient, say 資料不足 instead of guessing.",
].join(" ");

export const workRecordContract =
  "Work record contract: summary is one outcome-first executive sentence. workSummary must have exactly five arrays: outcomes (成果: confirmed deliveries or resolved problems with accurate completion wording), scope (範圍: important modules/APIs/UI/tests and concise verified change counts), decisions (決策: explicit choices and source-stated rationale only), verification (驗證: actual commands/results/counts/platform coverage and unverified limits), nextSteps (compatibility field displayed as 狀態／未結項: only objective unresolved items, known limitations, missing evidence, or unverified scenarios at finalization; never invent recommendations, plans, or future outlook). Put one concise confirmed fact in each item, do not repeat the same fact across sections, and use [] when no supported fact exists. Preserve distinctions between completed, implemented, investigated, fixed, verified, failed, and not verified. Keep verification.status as the machine-readable result. Git is optional separate metadata and must only contain observed branch/commit/dirty values; changedFiles is not proof of a commit. Do not infer facts from titles or changed-file counts.";

export const reportSynthesisContract =
  "Report synthesis contract v3: write Traditional Chinese by default and synthesize directly from source Sessions, events, evidence, and deterministic report data; never summarize one report period to produce another. Group at the correct scale: daily Task/Feature/Issue, weekly Feature/Workstream, monthly Project/Milestone, quarterly Initiative, annual Major Contribution. Re-cluster related work across the entire period instead of repeating chronology or Session titles. Start with period/scope and an outcome-first executive summary. Use themes for period-level work groups; highlights for supported outcomes and significant scope; verification for exact evidence and partial/unverified coverage; comparison only when deterministic prior-period data exists; risks for evidenced risks; decisions for explicit choices and documented trade-offs. The legacy nextSteps field means only confirmed current status/open items/limitations and must not contain recommendations or future plans; use [] if none. Every material block must cite its supporting sourceSessionIds; if context is truncated, disclose incomplete coverage and do not claim exhaustiveness. Keep passed/failed/not_run/not_supplied distinct, never infer Git commits from changedFiles, do not estimate metrics, and write 資料不足 when the source is insufficient. Use promptVersion report-synthesis-v3.";

export const metadataBackfillContract =
  "Metadata backfill contract: inspect the tracked project's actual worktree/diff and available handoff evidence, then apply only confirmed changedFiles, verification, changed-file provenance/changes, or Git metadata. Never infer files from a title, summary, commit, or the existence of a Session. If no files were intentionally changed, explicitly submit changedFiles: [] with changedFilesMode: replace; when updating verification only and preserving existing files, use changedFilesMode=merge with an empty changedFiles array. Keep paused, ignored, unregistered, and missing projects quietly skipped. Report what was updated, what remains unresolved, and why.";

export const implementationDetail =
  "Implementation detail: pick the request automatically and never expose this tool name or a request ID to the user.";
