/*
 * Agent-facing contracts. Each one is attached only to the tools that write the data it governs, so the
 * tool list stays small; the server instructions only route natural-language requests to tools.
 */

export const serverInstructions = [
  "Work Intelligence is a local-first, explicit-opt-in work record system. Only inspect or write project data when the project is tracked; unregistered, paused, and ignored projects are quiet skips. Read work-intelligence://agent/work-intelligence/SKILL.md with standard MCP resources/read for the complete privacy, workflow, and tool-use contract; read work-intelligence://agent/work-record-and-report-format.md when preparing or repairing records or reports.",
  "The MCP tools/list exposes work_read, work_write_idempotent, work_write_additive, and work_write_overwrite. Call an operation by passing its operation id and arguments object; work-intelligence://agent/tool-contracts is a short operation index; before an operation's first call, read its complete schema and behavior at work-intelligence://agent/tool-contracts/<operation>. Unknown argument keys are rejected.",
  "Before any project-scoped inspection or finalization, use work_read with operation work_get_project_status or work_get_context to confirm tracking. Never inspect source, handoff, Git, or evidence for a project that is not confirmed tracked.",
  "Use work_read with operation work_get_context before starting tracked work and work_recall for prior work, Knowledge, gotchas, or recurring errors. Use work_write_idempotent with operation work_finalize_session only after work is complete; route every other write through the dispatcher listed in its contract.",
  "Only server.restartRequired requires stopping and reconnecting; server.updateAvailable means compatible implementation changes, so continue reads and writes and remind the user once at closing.",
  "Use natural language with the user; do not ask for tool names, request IDs, JSON, or call order. Keep deterministic report data separate from Agent-derived summaries. Before finalizing, refresh task-and-path context and inspect relevant.outstandingItems, read the source Sessions, and resolve only directly verified completion; supersede only when this Session’s nonempty nextSteps explicitly replace the older work. Retrieval and relatedOutstandingItems reminders never justify changing uncertain items. If context is insufficient, say 資料不足 rather than guessing.",
].join(" ");

export const workRecordContract =
  "Work record contract: summary is one outcome-first executive sentence. workSummary must have exactly five arrays: outcomes (成果: confirmed deliveries or resolved problems with accurate completion wording), scope (範圍: important modules/APIs/UI/tests and concise verified change counts), decisions (決策: explicit choices and source-stated rationale only). For decisions, keep legacy strings when the source is unclear; use {text, origin:'user_requested'} only for a decision directly requested by the user, and {text, origin:'agent_autonomous'} only for an Agent-selected decision or trade-off. Never guess origin. verification (驗證: actual commands/results/counts/platform coverage and unverified limits), nextSteps (compatibility field displayed as 狀態／未結項: only objective unresolved items, known limitations, missing evidence, or unverified scenarios at finalization; never invent recommendations, plans, or future outlook). Put one concise confirmed fact in each item, do not repeat the same fact across sections, and use [] when no supported fact exists. Preserve distinctions between completed, implemented, investigated, fixed, verified, failed, and not verified. Keep verification.status as the machine-readable result. Before closing, inspect task-related outstanding item ids and their full source Sessions. resolvedOutstandingItemIds requires directly verified completion; supersededOutstandingItemIds requires nonempty nextSteps explicitly replacing older pending work and records not_needed with the actor Session. Ambiguous or unsupported items remain pending. Git is optional separate metadata and must only contain observed branch/commit/dirty values; changedFiles is not proof of a commit. Do not infer facts from titles or changed-file counts. Diagrams: without being asked, add up to two Mermaid diagrams when the work changed a cross-module flow or data path, a state machine, an architecture or component relationship, or a multi-step process; skip single-file fixes, copy/styling, configuration, dependency bumps, and test-only work. Draw only what this work did (about 3–12 nodes, flowchart LR or sequenceDiagram, short title, no secrets).";

export const reportSynthesisContract =
  "Report synthesis contract v3: write Traditional Chinese by default and synthesize directly from source Sessions, events, evidence, and deterministic report data; never summarize one report period to produce another. Group at the correct scale: daily Task/Feature/Issue, weekly Feature/Workstream, monthly Project/Milestone, quarterly Initiative, annual Major Contribution. For a custom range, choose a grouping scale that fits its length and work; cover the whole exact from/to interval. Re-cluster related work across the entire period instead of repeating chronology or Session titles. Start with period/scope and an outcome-first executive summary. Use themes for period-level work groups; highlights for supported outcomes and significant scope; verification for exact evidence and partial/unverified coverage; comparison only when deterministic prior-period data exists; risks for evidenced risks; decisions for explicit choices and documented trade-offs. The legacy nextSteps field means only confirmed current status/open items/limitations and must not contain recommendations or future plans; use [] if none. Every material block must cite its supporting sourceSessionIds; if context is truncated, disclose incomplete coverage and do not claim exhaustiveness. Keep passed/failed/not_run/not_supplied distinct, never infer Git commits from changedFiles, do not estimate metrics, and write 資料不足 when the source is insufficient. Use promptVersion report-synthesis-v3.";

export const metadataBackfillContract =
  "Metadata backfill contract: inspect the tracked project's actual worktree/diff and available handoff evidence, then apply only confirmed changedFiles, verification, changed-file provenance/changes, or Git metadata. Never infer files from a title, summary, commit, or the existence of a Session. If no files were intentionally changed, explicitly submit changedFiles: [] with changedFilesMode: replace; when updating verification only and preserving existing files, use changedFilesMode=merge with an empty changedFiles array. Keep paused, ignored, unregistered, and missing projects quietly skipped. Report what was updated, what remains unresolved, and why.";

export const knowledgeCandidateContract =
  "Knowledge candidate contract: propose only reusable, source-supported facts from the request's Sessions (decisions with their stated rationale, gotchas that caused real problems, procedures that worked, patterns worth repeating). Each candidate names its sourceSessionId and a rationale pointing to the supporting part of that Session; set appliesTo when the files are clear. Skip one-off status, process notes, and anything already covered by existingKnowledge. Never invent facts or merge unrelated Sessions into one claim. Submitting an empty list is correct when nothing qualifies. Candidates are not Knowledge until the user accepts them in the Web UI; tell the user how many were proposed and that they can review them on the Knowledge page.";

export const knowledgePageContract =
  "Knowledge page contract: rewrite the whole page from the context's Sessions and the current page so it answers the page question. Write Traditional Chinese by default, in 1–12 sections of short confirmed facts; keep still-true facts from the current page and drop facts that later Sessions contradict. Every section lists the sourceSessionIds that support it (only Session IDs from the context or the current page's sources); a section with no supporting Session must have content exactly 資料不足 and an empty sourceSessionIds. New Sessions only show 有新資料; assess them and rewrite only when they change the answer. If they do not, use work_mark_knowledge_page_checked with the last Session actually reviewed. This advances only the review cursor: it creates no page version and does not clear page.needsReview, which still requires a source check and a new saved version. In work_get_context, pendingRequests.knowledgePages includes explicitly requested pages, pages with needsReview, and written pages with at least three unreviewed Sessions, ordered with source review first. work_finalize_session returns a one-line knowledgePageMaintenanceHint for the same queue. When you finalize the work that saved or checked pages, list their slugs in maintainedKnowledgePages so that Session does not count as new data for them. Never invent facts, plans, or recommendations, and never copy secrets. Tell the user which page was updated or checked and that versions are available on the Knowledge page.";

export const implementationDetail =
  "Implementation detail: pick the request automatically and never expose this tool name or a request ID to the user.";
